[package]
name = "day-09"
version = "0.1.0"
authors = ["Kaleb Smart <kalebsma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.7.8"
